/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coral.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Coral(props) {
  const { nodes, materials } = useGLTF('/Coral.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.008']} position={[-13, 1, -7]} scale={[0.652, 1.59, 0.652]} />
    </group>
  )
}

useGLTF.preload('/Coral.glb')
