/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coral1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Coral1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder005_Material008_0.geometry} material={materials['Material.008']} position={[0.64, 0.492, 0.073]} rotation={[-1.643, 0.139, -2.501]} scale={0.12} />
    </group>
  )
}

useGLTF.preload('/Coral1.glb')
