/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coral2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Coral2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane005_Material001_0.geometry} material={materials['Material.001']} position={[0.649, 0.188, 0.604]} rotation={[-Math.PI, 1.331, -Math.PI]} scale={0.245} />
    </group>
  )
}

useGLTF.preload('/Coral2.glb')
