/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coral3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Coral3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.002']} position={[0.569, 0.547, -0.079]} rotation={[-Math.PI / 2, 0, -0.332]} scale={1.006} />
      <mesh geometry={nodes.Cylinder002_Material002_0.geometry} material={materials['Material.002']} position={[0.527, 0.548, -0.085]} rotation={[-Math.PI / 2, 0, 2.17]} scale={0.678} />
    </group>
  )
}

useGLTF.preload('/Coral3.glb')
