/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FishAnimation3.glb 
*/

import React, { useState, useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model({animationPlay, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/FishAnimation3.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (animationPlay) {
      actions.FishingCast.reset().play();
    } else if (!animationPlay) {
      actions.FishingIdle.reset().play();
    }
  }, [animationPlay, actions.FishingCast, actions.FishingIdle]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsCurve" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Armature" position={[0, 1.3, 0.2]} rotation={[Math.PI / 2, 0, 0]} scale={2.047}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Cone001" geometry={nodes.Cone001.geometry} material={materials['Material.016']} skeleton={nodes.Cone001.skeleton} />
          <skinnedMesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.017']} skeleton={nodes.Cylinder.skeleton} />
          <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.018']} skeleton={nodes.Cylinder001.skeleton} />
          <skinnedMesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} skeleton={nodes.Cylinder002.skeleton} />
          <skinnedMesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} skeleton={nodes.Cylinder003.skeleton} />
          <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.019']} skeleton={nodes.Cylinder004.skeleton} />
          <skinnedMesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.022']} skeleton={nodes.Cylinder005.skeleton} />
          <skinnedMesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.020']} skeleton={nodes.Cylinder006.skeleton} />
          <skinnedMesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Material.023']} skeleton={nodes.Cylinder007.skeleton} />
          <skinnedMesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['Material.025']} skeleton={nodes.Cylinder008.skeleton} />
          <skinnedMesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['Material.028']} skeleton={nodes.Cylinder009.skeleton} />
          <skinnedMesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Material.030']} skeleton={nodes.Cylinder010.skeleton} />
          <skinnedMesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Material.027']} skeleton={nodes.Cylinder011.skeleton} />
          <skinnedMesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.026']} skeleton={nodes.Icosphere.skeleton} />
          <skinnedMesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} skeleton={nodes.Icosphere001.skeleton} />
          <skinnedMesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials['Material.024']} skeleton={nodes.Icosphere002.skeleton} />
          <skinnedMesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} skeleton={nodes.Icosphere003.skeleton} />
          <skinnedMesh name="Icosphere004" geometry={nodes.Icosphere004.geometry} material={materials['Material.029']} skeleton={nodes.Icosphere004.skeleton} />
          <skinnedMesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} skeleton={nodes.Icosphere005.skeleton} />
          <skinnedMesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={materials['Material.031']} skeleton={nodes.Icosphere006.skeleton} />
          <skinnedMesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.021']} skeleton={nodes.Sphere.skeleton} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Material} position={[0, 1, 3.5]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.Material} position={[0, 1, 3.504]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials.Material} position={[0, 1, 5.504]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/FishAnimation3.glb')
