/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SeaTurtle.glb 
*/

import React, { useRef, useState, useEffect } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function SeaTurtle(props) {

  const [dirSwitch, setDirSwitch] = useState(false);
  const [radiusFac, setRadiusFac] = useState(0.03); // Increased rotation speed

  const group = useRef();
  const { scene, animations } = useGLTF('/SeaTurtle.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const [pos, setPos] = useState([0, 0, 0]);
  const [rotY, setRotY] = useState(0);

  useEffect(() => {
    setRadiusFac(Math.random() * 0.01 + 0.02); // Faster random rotation speed
    setPos([
      20 * (Math.random() - 0.5),
      props.index * 10 - 5,
      10 * (Math.random() - 0.5),
    ]);
    let angle = Math.random() * 2 * Math.PI;
    setRotY(angle);
  }, []);

  useEffect(() => {
    group.current.rotation.y = rotY;
  }, [rotY]);

  useEffect(() => {
    actions?.["Armature.001Action"]?.reset().play();
  }, [actions]);

  useFrame(() => {
    if (rotY >= 2 * Math.PI || rotY < -2 * Math.PI) {
      setDirSwitch((prev) => !prev);
      setRotY(0);
      return;
    }
    setRotY((prev) => {
      if (dirSwitch) return prev + radiusFac;
      return prev - radiusFac;
    });
    setPos((prev) => {
      return [
        prev[0] - 0.05 * Math.sin(rotY), // Negated for opposite direction
        prev[1],
        prev[2] - 0.05 * Math.cos(rotY), // Negated for opposite direction
      ];
    });
  });

  return (
    <group ref={group} {...props} position={pos} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[-1.562, 0, -0.012]} scale={2.57}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone007} />
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.007']} skeleton={nodes.Cube001.skeleton} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.007']} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.007']} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.004']} skeleton={nodes.Cube018.skeleton} />
          <skinnedMesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.001']} skeleton={nodes.Cube019.skeleton} />
          <skinnedMesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.007']} skeleton={nodes.Cube020.skeleton} />
          <skinnedMesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.006']} skeleton={nodes.Cube021.skeleton} />
          <skinnedMesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.005']} skeleton={nodes.Cube022.skeleton} />
          <skinnedMesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.002']} skeleton={nodes.Cube023.skeleton} />
          <skinnedMesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.003']} skeleton={nodes.Cube024.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SeaTurtle.glb')
